### ISSUE TITLE
不能正常运行

### ISSUE THREAD

**Issue by xiaoshui05** [Flowingsun007/LyonBlog#1]
- 推测是ddl和代码的版本不一致，错误日志：
```java
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'targetUrl' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
```
- target目录太大了，这个可以去掉的

**Comment by Flowingsun007** [comment]
你好，target已经去掉了，现在的ddl和dml也已经更新，应该是可以的了~
